//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Framework.Input.Service {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactState", Namespace="http://schemas.datacontract.org/2004/07/Multitouch.Contracts")]
    internal enum ContactState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Removed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Moved = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Input.Service.IApplicationInterface", CallbackContract=typeof(Multitouch.Framework.Input.Service.IApplicationInterfaceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    internal interface IApplicationInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationInterface/Subscribe", ReplyAction="http://tempuri.org/IApplicationInterface/SubscribeResponse")]
        void Subscribe(System.IntPtr windowHandle);
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, Action="http://tempuri.org/IApplicationInterface/Unsubscribe", ReplyAction="http://tempuri.org/IApplicationInterface/UnsubscribeResponse")]
        void Unsubscribe();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal interface IApplicationInterfaceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IApplicationInterface/ContactChanged")]
        void ContactChanged(int id, double x, double y, double width, double height, Multitouch.Framework.Input.Service.ContactState state);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal interface IApplicationInterfaceChannel : Multitouch.Framework.Input.Service.IApplicationInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal partial class ApplicationInterfaceClient : System.ServiceModel.DuplexClientBase<Multitouch.Framework.Input.Service.IApplicationInterface>, Multitouch.Framework.Input.Service.IApplicationInterface {
        
        public ApplicationInterfaceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ApplicationInterfaceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ApplicationInterfaceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationInterfaceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationInterfaceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe(System.IntPtr windowHandle) {
            base.Channel.Subscribe(windowHandle);
        }
        
        public void Unsubscribe() {
            base.Channel.Unsubscribe();
        }
    }
}
