//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class ContactChangedEventArgsHostAdapter
    {
        internal static Multitouch.Contracts.ContactChangedEventArgs ContractToViewAdapter(Multitouch.Contracts.Contracts.IContactChangedEventArgsContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(ContactChangedEventArgsViewToContractHostAdapter))))
            {
                return ((ContactChangedEventArgsViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new ContactChangedEventArgsContractToViewHostAdapter(contract);
            }
        }
        internal static Multitouch.Contracts.Contracts.IContactChangedEventArgsContract ViewToContractAdapter(Multitouch.Contracts.ContactChangedEventArgs view)
        {
            if (view.GetType().Equals(typeof(ContactChangedEventArgsContractToViewHostAdapter)))
            {
                return ((ContactChangedEventArgsContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new ContactChangedEventArgsViewToContractHostAdapter(view);
            }
        }
    }
}

