//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class ContactChangedEventArgsViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, Multitouch.Contracts.Contracts.IContactChangedEventArgsContract
    {
        private Multitouch.Contracts.ContactChangedEventArgs _view;
        public ContactChangedEventArgsViewToContractHostAdapter(Multitouch.Contracts.ContactChangedEventArgs view)
        {
            _view = view;
        }
        public Multitouch.Contracts.Contracts.IContactContract Contact
        {
            get
            {
                return Multitouch.Contracts.HostSideAdapters.IContactHostAdapter.ViewToContractAdapter(_view.Contact);
            }
        }
        internal Multitouch.Contracts.ContactChangedEventArgs GetSourceView()
        {
            return _view;
        }
    }
}

