//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class IContactDataContractToViewHostAdapter : Multitouch.Contracts.IContactData
    {
        private Multitouch.Contracts.Contracts.IContactDataContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IContactDataContractToViewHostAdapter()
        {
        }
        public IContactDataContractToViewHostAdapter(Multitouch.Contracts.Contracts.IContactDataContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public int Id
        {
            get
            {
                return _contract.Id;
            }
        }
        public System.Windows.Rect Bounds
        {
            get
            {
                return _contract.Bounds;
            }
        }
        public double X
        {
            get
            {
                return _contract.X;
            }
        }
        public double Y
        {
            get
            {
                return _contract.Y;
            }
        }
        public double Width
        {
            get
            {
                return _contract.Width;
            }
        }
        public double Height
        {
            get
            {
                return _contract.Height;
            }
        }
        public double Angle
        {
            get
            {
                return _contract.Angle;
            }
        }
        public Multitouch.Contracts.ContactState State
        {
            get
            {
                return Multitouch.Contracts.HostSideAdapters.ContactStateHostAdapter.ContractToViewAdapter(_contract.State);
            }
        }
        internal Multitouch.Contracts.Contracts.IContactDataContract GetSourceContract()
        {
            return _contract;
        }
    }
}

