//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class IContactHostAdapter
    {
        internal static Multitouch.Contracts.IContact ContractToViewAdapter(Multitouch.Contracts.Contracts.IContactContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IContactViewToContractHostAdapter))))
            {
                return ((IContactViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IContactContractToViewHostAdapter(contract);
            }
        }
        internal static Multitouch.Contracts.Contracts.IContactContract ViewToContractAdapter(Multitouch.Contracts.IContact view)
        {
            if (view.GetType().Equals(typeof(IContactContractToViewHostAdapter)))
            {
                return ((IContactContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IContactViewToContractHostAdapter(view);
            }
        }
    }
}

