//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class IFrameDataContractToViewHostAdapter : Multitouch.Contracts.IFrameData
    {
        private Multitouch.Contracts.Contracts.IFrameDataContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IFrameDataContractToViewHostAdapter()
        {
        }
        public IFrameDataContractToViewHostAdapter(Multitouch.Contracts.Contracts.IFrameDataContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public System.Collections.Generic.IList<Multitouch.Contracts.IImageData> Image
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIList<Multitouch.Contracts.Contracts.IImageDataContract, Multitouch.Contracts.IImageData>(_contract.Image, Multitouch.Contracts.HostSideAdapters.IImageDataHostAdapter.ContractToViewAdapter, Multitouch.Contracts.HostSideAdapters.IImageDataHostAdapter.ViewToContractAdapter);
            }
        }
        internal Multitouch.Contracts.Contracts.IFrameDataContract GetSourceContract()
        {
            return _contract;
        }
    }
}

