//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class IFrameDataHostAdapter
    {
        internal static Multitouch.Contracts.IFrameData ContractToViewAdapter(Multitouch.Contracts.Contracts.IFrameDataContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IFrameDataViewToContractHostAdapter))))
            {
                return ((IFrameDataViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IFrameDataContractToViewHostAdapter(contract);
            }
        }
        internal static Multitouch.Contracts.Contracts.IFrameDataContract ViewToContractAdapter(Multitouch.Contracts.IFrameData view)
        {
            if (view.GetType().Equals(typeof(IFrameDataContractToViewHostAdapter)))
            {
                return ((IFrameDataContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IFrameDataViewToContractHostAdapter(view);
            }
        }
    }
}

