//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class IInputEventHandlerContractToViewHostAdapter
    {
        private Multitouch.Contracts.Contracts.IInputEventHandlerContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        public IInputEventHandlerContractToViewHostAdapter(Multitouch.Contracts.Contracts.IInputEventHandlerContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public void Handler(object sender, Multitouch.Contracts.InputDataEventArgs args)
        {
            _contract.Handler(Multitouch.Contracts.HostSideAdapters.InputDataEventArgsHostAdapter.ViewToContractAdapter(args));
        }
        internal Multitouch.Contracts.Contracts.IInputEventHandlerContract GetSourceContract()
        {
            return _contract;
        }
    }
}

