//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class InputTypeHostAdapter
    {
        internal static Multitouch.Contracts.InputType ContractToViewAdapter(Multitouch.Contracts.Contracts.InputType contract)
        {
            return ((Multitouch.Contracts.InputType)(contract));
        }
        internal static Multitouch.Contracts.Contracts.InputType ViewToContractAdapter(Multitouch.Contracts.InputType view)
        {
            return ((Multitouch.Contracts.Contracts.InputType)(view));
        }
    }
}

