//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class InputDataEventArgsContractToViewHostAdapter : Multitouch.Contracts.InputDataEventArgs
    {
        private Multitouch.Contracts.Contracts.IInputDataEventArgsContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static InputDataEventArgsContractToViewHostAdapter()
        {
        }
        public InputDataEventArgsContractToViewHostAdapter(Multitouch.Contracts.Contracts.IInputDataEventArgsContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public override Multitouch.Contracts.InputType Type
        {
            get
            {
                return Multitouch.Contracts.HostSideAdapters.InputTypeHostAdapter.ContractToViewAdapter(_contract.Type);
            }
        }
        public override object Data
        {
            get
            {
                return _contract.Data;
            }
        }
        internal Multitouch.Contracts.Contracts.IInputDataEventArgsContract GetSourceContract()
        {
            return _contract;
        }
    }
}

