//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class InputDataEventArgsHostAdapter
    {
        internal static Multitouch.Contracts.InputDataEventArgs ContractToViewAdapter(Multitouch.Contracts.Contracts.IInputDataEventArgsContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(InputDataEventArgsViewToContractHostAdapter))))
            {
                return ((InputDataEventArgsViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new InputDataEventArgsContractToViewHostAdapter(contract);
            }
        }
        internal static Multitouch.Contracts.Contracts.IInputDataEventArgsContract ViewToContractAdapter(Multitouch.Contracts.InputDataEventArgs view)
        {
            if (view.GetType().Equals(typeof(InputDataEventArgsContractToViewHostAdapter)))
            {
                return ((InputDataEventArgsContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new InputDataEventArgsViewToContractHostAdapter(view);
            }
        }
    }
}

