//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    [System.AddIn.Pipeline.HostAdapterAttribute()]
    public class IProviderContractToViewHostAdapter : Multitouch.Contracts.IProvider
    {
        private Multitouch.Contracts.Contracts.IProviderContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        private Multitouch.Contracts.HostSideAdapters.IContactChangedEventHandlerViewToContractHostAdapter ContactChanged_Handler;
        private static System.Reflection.MethodInfo s_ContactChangedAddFire;
		public event System.EventHandler<Multitouch.Contracts.ContactChangedEventArgs>ContactChanged{
			add{
				if (_ContactChanged == null)
				{
					_contract.ContactChangedAdd(ContactChanged_Handler);
				}
				_ContactChanged += value;
				}
			remove{
					_ContactChanged -= value;
				if (_ContactChanged == null)
				{
					_contract.ContactChangedRemove(ContactChanged_Handler);
				}
				}
		}
        static IProviderContractToViewHostAdapter()
        {
            s_ContactChangedAddFire = typeof(IProviderContractToViewHostAdapter).GetMethod("Fire_ContactChanged", ((System.Reflection.BindingFlags)(36)));
        }
        public IProviderContractToViewHostAdapter(Multitouch.Contracts.Contracts.IProviderContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
            ContactChanged_Handler = new Multitouch.Contracts.HostSideAdapters.IContactChangedEventHandlerViewToContractHostAdapter(this, s_ContactChangedAddFire);
        }
        public bool IsRunning
        {
            get
            {
                return _contract.IsRunning;
            }
        }
        private event System.EventHandler<Multitouch.Contracts.ContactChangedEventArgs> _ContactChanged;
        public void Start()
        {
            _contract.Start();
        }
        public void Stop()
        {
            _contract.Stop();
        }
        internal virtual void Fire_ContactChanged(Multitouch.Contracts.ContactChangedEventArgs args)
        {
            if ((_ContactChanged == null))
            {
            }
            else
            {
                _ContactChanged.Invoke(this, args);
            }
        }
        internal Multitouch.Contracts.Contracts.IProviderContract GetSourceContract()
        {
            return _contract;
        }
    }
}

