//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class IProviderHostAdapter
    {
        internal static Multitouch.Contracts.IProvider ContractToViewAdapter(Multitouch.Contracts.Contracts.IProviderContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IProviderViewToContractHostAdapter))))
            {
                return ((IProviderViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IProviderContractToViewHostAdapter(contract);
            }
        }
        internal static Multitouch.Contracts.Contracts.IProviderContract ViewToContractAdapter(Multitouch.Contracts.IProvider view)
        {
            if (view.GetType().Equals(typeof(IProviderContractToViewHostAdapter)))
            {
                return ((IProviderContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IProviderViewToContractHostAdapter(view);
            }
        }
    }
}

