//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.HostSideAdapters
{
    
    public class NewFrameEventArgsViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, Multitouch.Contracts.Contracts.INewFrameEventArgsContract
    {
        private Multitouch.Contracts.NewFrameEventArgs _view;
        public NewFrameEventArgsViewToContractHostAdapter(Multitouch.Contracts.NewFrameEventArgs view)
        {
            _view = view;
        }
        public System.AddIn.Contract.IListContract<Multitouch.Contracts.Contracts.IImageDataContract> Images
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<Multitouch.Contracts.IImageData, Multitouch.Contracts.Contracts.IImageDataContract>(_view.Images, Multitouch.Contracts.HostSideAdapters.IImageDataHostAdapter.ViewToContractAdapter, Multitouch.Contracts.HostSideAdapters.IImageDataHostAdapter.ContractToViewAdapter);
            }
        }
        public System.AddIn.Contract.IListContract<Multitouch.Contracts.Contracts.IContactDataContract> Contacts
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<Multitouch.Contracts.IContactData, Multitouch.Contracts.Contracts.IContactDataContract>(_view.Contacts, Multitouch.Contracts.HostSideAdapters.IContactDataHostAdapter.ViewToContractAdapter, Multitouch.Contracts.HostSideAdapters.IContactDataHostAdapter.ContractToViewAdapter);
            }
        }
        public long Timestamp
        {
            get
            {
                return _view.Timestamp;
            }
        }
        internal Multitouch.Contracts.NewFrameEventArgs GetSourceView()
        {
            return _view;
        }
    }
}

