//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class ContactStateAddInAdapter
    {
        internal static Multitouch.Contracts.ContactState ContractToViewAdapter(Multitouch.Contracts.Contracts.ContactState contract)
        {
            return ((Multitouch.Contracts.ContactState)(contract));
        }
        internal static Multitouch.Contracts.Contracts.ContactState ViewToContractAdapter(Multitouch.Contracts.ContactState view)
        {
            return ((Multitouch.Contracts.Contracts.ContactState)(view));
        }
    }
}

