//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class ContactChangedEventArgsAddInAdapter
    {
        internal static Multitouch.Contracts.ContactChangedEventArgs ContractToViewAdapter(Multitouch.Contracts.Contracts.IContactChangedEventArgsContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(ContactChangedEventArgsViewToContractAddInAdapter))))
            {
                return ((ContactChangedEventArgsViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new ContactChangedEventArgsContractToViewAddInAdapter(contract);
            }
        }
        internal static Multitouch.Contracts.Contracts.IContactChangedEventArgsContract ViewToContractAdapter(Multitouch.Contracts.ContactChangedEventArgs view)
        {
            if (view.GetType().Equals(typeof(ContactChangedEventArgsContractToViewAddInAdapter)))
            {
                return ((ContactChangedEventArgsContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new ContactChangedEventArgsViewToContractAddInAdapter(view);
            }
        }
    }
}

