//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IContactDataViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Multitouch.Contracts.Contracts.IContactDataContract
    {
        private Multitouch.Contracts.IContactData _view;
        public IContactDataViewToContractAddInAdapter(Multitouch.Contracts.IContactData view)
        {
            _view = view;
        }
        public int Id
        {
            get
            {
                return _view.Id;
            }
        }
        public System.Windows.Rect Bounds
        {
            get
            {
                return _view.Bounds;
            }
        }
        public double X
        {
            get
            {
                return _view.X;
            }
        }
        public double Y
        {
            get
            {
                return _view.Y;
            }
        }
        public double Width
        {
            get
            {
                return _view.Width;
            }
        }
        public double Height
        {
            get
            {
                return _view.Height;
            }
        }
        public double Angle
        {
            get
            {
                return _view.Angle;
            }
        }
        public Multitouch.Contracts.Contracts.ContactState State
        {
            get
            {
                return Multitouch.Contracts.AddInSideAdapters.ContactStateAddInAdapter.ViewToContractAdapter(_view.State);
            }
        }
        internal Multitouch.Contracts.IContactData GetSourceView()
        {
            return _view;
        }
    }
}

