//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IContactDataAddInAdapter
    {
        internal static Multitouch.Contracts.IContactData ContractToViewAdapter(Multitouch.Contracts.Contracts.IContactDataContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IContactDataViewToContractAddInAdapter))))
            {
                return ((IContactDataViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IContactDataContractToViewAddInAdapter(contract);
            }
        }
        internal static Multitouch.Contracts.Contracts.IContactDataContract ViewToContractAdapter(Multitouch.Contracts.IContactData view)
        {
            if (view.GetType().Equals(typeof(IContactDataContractToViewAddInAdapter)))
            {
                return ((IContactDataContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IContactDataViewToContractAddInAdapter(view);
            }
        }
    }
}

