//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IContactContractToViewAddInAdapter : Multitouch.Contracts.IContact
    {
        private Multitouch.Contracts.Contracts.IContactContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IContactContractToViewAddInAdapter()
        {
        }
        public IContactContractToViewAddInAdapter(Multitouch.Contracts.Contracts.IContactContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public int Id
        {
            get
            {
                return _contract.Id;
            }
        }
        public double X
        {
            get
            {
                return _contract.X;
            }
        }
        public double Y
        {
            get
            {
                return _contract.Y;
            }
        }
        public double Width
        {
            get
            {
                return _contract.Width;
            }
        }
        public double Height
        {
            get
            {
                return _contract.Height;
            }
        }
        public Multitouch.Contracts.ContactState State
        {
            get
            {
                return Multitouch.Contracts.AddInSideAdapters.ContactStateAddInAdapter.ContractToViewAdapter(_contract.State);
            }
        }
        internal Multitouch.Contracts.Contracts.IContactContract GetSourceContract()
        {
            return _contract;
        }
    }
}

