//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IContactDataViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Multitouch.Contracts.Contracts.IContactDataContract
    {
        private Multitouch.Contracts.IContactData _view;
        public IContactDataViewToContractAddInAdapter(Multitouch.Contracts.IContactData view)
        {
            _view = view;
        }
        public int Id
        {
            get
            {
                return _view.Id;
            }
        }
        public System.Windows.Rect Bounds
        {
            get
            {
                return _view.Bounds;
            }
        }
        public System.Windows.Point Position
        {
            get
            {
                return _view.Position;
            }
        }
        public double Orientation
        {
            get
            {
                return _view.Orientation;
            }
        }
        public double Area
        {
            get
            {
                return _view.Area;
            }
        }
        public double MajorAxis
        {
            get
            {
                return _view.MajorAxis;
            }
        }
        public double MinorAxis
        {
            get
            {
                return _view.MinorAxis;
            }
        }
        public Multitouch.Contracts.Contracts.ContactState State
        {
            get
            {
                return Multitouch.Contracts.AddInSideAdapters.ContactStateAddInAdapter.ViewToContractAdapter(_view.State);
            }
        }
        internal Multitouch.Contracts.IContactData GetSourceView()
        {
            return _view;
        }
    }
}

