//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IContactChangedEventHandlerViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Multitouch.Contracts.Contracts.IContactChangedEventHandlerContract
    {
        private object _view;
        private System.Reflection.MethodInfo _event;
        public IContactChangedEventHandlerViewToContractAddInAdapter(object view, System.Reflection.MethodInfo eventProp)
        {
            _view = view;
            _event = eventProp;
        }
        public void Handler(Multitouch.Contracts.Contracts.IContactChangedEventArgsContract args)
        {
            Multitouch.Contracts.AddInSideAdapters.ContactChangedEventArgsContractToViewAddInAdapter adaptedArgs;
            adaptedArgs = new Multitouch.Contracts.AddInSideAdapters.ContactChangedEventArgsContractToViewAddInAdapter(args);
            object[] argsArray = new object[1];
            argsArray[0] = adaptedArgs;
            _event.Invoke(_view, argsArray);
        }
        internal object GetSourceView()
        {
            return _view;
        }
    }
}

