//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IFrameDataViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Multitouch.Contracts.Contracts.IFrameDataContract
    {
        private Multitouch.Contracts.IFrameData _view;
        public IFrameDataViewToContractAddInAdapter(Multitouch.Contracts.IFrameData view)
        {
            _view = view;
        }
        public System.AddIn.Contract.IListContract<Multitouch.Contracts.Contracts.IImageDataContract> Image
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<Multitouch.Contracts.IImageData, Multitouch.Contracts.Contracts.IImageDataContract>(_view.Image, Multitouch.Contracts.AddInSideAdapters.IImageDataAddInAdapter.ViewToContractAdapter, Multitouch.Contracts.AddInSideAdapters.IImageDataAddInAdapter.ContractToViewAdapter);
            }
        }
        internal Multitouch.Contracts.IFrameData GetSourceView()
        {
            return _view;
        }
    }
}

