//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IFrameDataAddInAdapter
    {
        internal static Multitouch.Contracts.IFrameData ContractToViewAdapter(Multitouch.Contracts.Contracts.IFrameDataContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IFrameDataViewToContractAddInAdapter))))
            {
                return ((IFrameDataViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IFrameDataContractToViewAddInAdapter(contract);
            }
        }
        internal static Multitouch.Contracts.Contracts.IFrameDataContract ViewToContractAdapter(Multitouch.Contracts.IFrameData view)
        {
            if (view.GetType().Equals(typeof(IFrameDataContractToViewAddInAdapter)))
            {
                return ((IFrameDataContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IFrameDataViewToContractAddInAdapter(view);
            }
        }
    }
}

