//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IImageDataContractToViewAddInAdapter : Multitouch.Contracts.IImageData
    {
        private Multitouch.Contracts.Contracts.IImageDataContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IImageDataContractToViewAddInAdapter()
        {
        }
        public IImageDataContractToViewAddInAdapter(Multitouch.Contracts.Contracts.IImageDataContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public int Width
        {
            get
            {
                return _contract.Width;
            }
        }
        public int Height
        {
            get
            {
                return _contract.Height;
            }
        }
        public int Stride
        {
            get
            {
                return _contract.Stride;
            }
        }
        public int BitsPerPixel
        {
            get
            {
                return _contract.BitsPerPixel;
            }
        }
        public Multitouch.Contracts.ImageType Type
        {
            get
            {
                return Multitouch.Contracts.AddInSideAdapters.ImageTypeAddInAdapter.ContractToViewAdapter(_contract.Type);
            }
        }
        public byte[] Data
        {
            get
            {
                return _contract.Data;
            }
        }
        internal Multitouch.Contracts.Contracts.IImageDataContract GetSourceContract()
        {
            return _contract;
        }
    }
}

