//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IImageDataViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Multitouch.Contracts.Contracts.IImageDataContract
    {
        private Multitouch.Contracts.IImageData _view;
        public IImageDataViewToContractAddInAdapter(Multitouch.Contracts.IImageData view)
        {
            _view = view;
        }
        public int Width
        {
            get
            {
                return _view.Width;
            }
        }
        public int Height
        {
            get
            {
                return _view.Height;
            }
        }
        public int Stride
        {
            get
            {
                return _view.Stride;
            }
        }
        public int BitsPerPixel
        {
            get
            {
                return _view.BitsPerPixel;
            }
        }
        public Multitouch.Contracts.Contracts.ImageType Type
        {
            get
            {
                return Multitouch.Contracts.AddInSideAdapters.ImageTypeAddInAdapter.ViewToContractAdapter(_view.Type);
            }
        }
        public byte[] Data
        {
            get
            {
                return _view.Data;
            }
        }
        internal Multitouch.Contracts.IImageData GetSourceView()
        {
            return _view;
        }
    }
}

