//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IImageDataAddInAdapter
    {
        internal static Multitouch.Contracts.IImageData ContractToViewAdapter(Multitouch.Contracts.Contracts.IImageDataContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IImageDataViewToContractAddInAdapter))))
            {
                return ((IImageDataViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IImageDataContractToViewAddInAdapter(contract);
            }
        }
        internal static Multitouch.Contracts.Contracts.IImageDataContract ViewToContractAdapter(Multitouch.Contracts.IImageData view)
        {
            if (view.GetType().Equals(typeof(IImageDataContractToViewAddInAdapter)))
            {
                return ((IImageDataContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IImageDataViewToContractAddInAdapter(view);
            }
        }
    }
}

