//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IInputPreviewHandlerAddInAdapter
    {
        internal static Multitouch.Contracts.IInputPreviewHandler ContractToViewAdapter(Multitouch.Contracts.Contracts.IInputPreviewHandlerContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IInputPreviewHandlerViewToContractAddInAdapter))))
            {
                return ((IInputPreviewHandlerViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IInputPreviewHandlerContractToViewAddInAdapter(contract);
            }
        }
        internal static Multitouch.Contracts.Contracts.IInputPreviewHandlerContract ViewToContractAdapter(Multitouch.Contracts.IInputPreviewHandler view)
        {
            if (view.GetType().Equals(typeof(IInputPreviewHandlerContractToViewAddInAdapter)))
            {
                return ((IInputPreviewHandlerContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IInputPreviewHandlerViewToContractAddInAdapter(view);
            }
        }
    }
}

