//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    [System.AddIn.Pipeline.AddInAdapterAttribute()]
    public class IInputPreviewHandlerViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Multitouch.Contracts.Contracts.IInputPreviewHandlerContract
    {
        private Multitouch.Contracts.IInputPreviewHandler _view;
        public IInputPreviewHandlerViewToContractAddInAdapter(Multitouch.Contracts.IInputPreviewHandler view)
        {
            _view = view;
        }
        public int Order
        {
            get
            {
                return _view.Order;
            }
        }
        public virtual void Start()
        {
            _view.Start();
        }
        public virtual void Stop()
        {
            _view.Stop();
        }
        public virtual Multitouch.Contracts.IPreviewResultContract Handle(Multitouch.Contracts.Contracts.IContactContract contact)
        {
            return Multitouch.AddInSideAdapters.IPreviewResultAddInAdapter.ViewToContractAdapter(_view.Handle(Multitouch.Contracts.AddInSideAdapters.IContactAddInAdapter.ContractToViewAdapter(contact)));
        }
        internal Multitouch.Contracts.IInputPreviewHandler GetSourceView()
        {
            return _view;
        }
    }
}

