//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IInputPostHandlerContractToViewAddInAdapter : Multitouch.Contracts.IInputPostHandler
    {
        private Multitouch.Contracts.Contracts.IInputPostHandlerContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IInputPostHandlerContractToViewAddInAdapter()
        {
        }
        public IInputPostHandlerContractToViewAddInAdapter(Multitouch.Contracts.Contracts.IInputPostHandlerContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public int Order
        {
            get
            {
                return _contract.Order;
            }
        }
        public void Start()
        {
            _contract.Start();
        }
        public void Stop()
        {
            _contract.Stop();
        }
        public void Handle(System.IntPtr windowHandle, IContact contact)
        {
            _contract.Handle(windowHandle, Multitouch.Contracts.AddInSideAdapters.IContactAddInAdapter.ViewToContractAdapter(contact));
        }
        internal Multitouch.Contracts.Contracts.IInputPostHandlerContract GetSourceContract()
        {
            return _contract;
        }
    }
}

