//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IInputPreviewHandlerContractToViewAddInAdapter : Multitouch.Contracts.IInputPreviewHandler
    {
        private Multitouch.Contracts.Contracts.IInputPreviewHandlerContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IInputPreviewHandlerContractToViewAddInAdapter()
        {
        }
        public IInputPreviewHandlerContractToViewAddInAdapter(Multitouch.Contracts.Contracts.IInputPreviewHandlerContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public Multitouch.IPreviewResult Handle(IContact contact)
        {
            return Multitouch.AddInSideAdapters.IPreviewResultAddInAdapter.ContractToViewAdapter(_contract.Handle(Multitouch.Contracts.AddInSideAdapters.IContactAddInAdapter.ViewToContractAdapter(contact)));
        }
        internal Multitouch.Contracts.Contracts.IInputPreviewHandlerContract GetSourceContract()
        {
            return _contract;
        }
    }
}

