//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class ImageTypeAddInAdapter
    {
        internal static Multitouch.Contracts.ImageType ContractToViewAdapter(Multitouch.Contracts.Contracts.ImageType contract)
        {
            return ((Multitouch.Contracts.ImageType)(contract));
        }
        internal static Multitouch.Contracts.Contracts.ImageType ViewToContractAdapter(Multitouch.Contracts.ImageType view)
        {
            return ((Multitouch.Contracts.Contracts.ImageType)(view));
        }
    }
}

