//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class InputDataEventArgsViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Multitouch.Contracts.Contracts.IInputDataEventArgsContract
    {
        private Multitouch.Contracts.InputDataEventArgs _view;
        public InputDataEventArgsViewToContractAddInAdapter(Multitouch.Contracts.InputDataEventArgs view)
        {
            _view = view;
        }
        public Multitouch.Contracts.Contracts.InputType Type
        {
            get
            {
                return Multitouch.Contracts.AddInSideAdapters.InputTypeAddInAdapter.ViewToContractAdapter(_view.Type);
            }
        }
        public object Data
        {
            get
            {
                return _view.Data;
            }
        }
        internal Multitouch.Contracts.InputDataEventArgs GetSourceView()
        {
            return _view;
        }
    }
}

