//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.AddInSideAdapters
{
    
    public class IPreviewResultViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Multitouch.Contracts.IPreviewResultContract
    {
        private Multitouch.IPreviewResult _view;
        public IPreviewResultViewToContractAddInAdapter(Multitouch.IPreviewResult view)
        {
            _view = view;
        }
        public Multitouch.Contracts.Contracts.IContactContract Contact
        {
            get
            {
                return Multitouch.Contracts.AddInSideAdapters.IContactAddInAdapter.ViewToContractAdapter(_view.Contact);
            }
        }
        public System.IntPtr HWnd
        {
            get
            {
                return _view.HWnd;
            }
        }
        public bool Handled
        {
            get
            {
                return _view.Handled;
            }
        }
        internal Multitouch.IPreviewResult GetSourceView()
        {
            return _view;
        }
    }
}

