//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IPreviewResultAddInAdapter
    {
        internal static Multitouch.Contracts.IPreviewResult ContractToViewAdapter(Multitouch.Contracts.Contracts.IPreviewResultContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IPreviewResultViewToContractAddInAdapter))))
            {
                return ((IPreviewResultViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IPreviewResultContractToViewAddInAdapter(contract);
            }
        }
        internal static Multitouch.Contracts.Contracts.IPreviewResultContract ViewToContractAdapter(Multitouch.Contracts.IPreviewResult view)
        {
            if (view.GetType().Equals(typeof(IPreviewResultContractToViewAddInAdapter)))
            {
                return ((IPreviewResultContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IPreviewResultViewToContractAddInAdapter(view);
            }
        }
    }
}

