//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IPreviewResultContractToViewAddInAdapter : Multitouch.Contracts.IPreviewResult
    {
        private Multitouch.Contracts.Contracts.IPreviewResultContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IPreviewResultContractToViewAddInAdapter()
        {
        }
        public IPreviewResultContractToViewAddInAdapter(Multitouch.Contracts.Contracts.IPreviewResultContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public Multitouch.Contracts.IContact Contact
        {
            get
            {
                return Multitouch.Contracts.AddInSideAdapters.IContactAddInAdapter.ContractToViewAdapter(_contract.Contact);
            }
        }
        public System.IntPtr HWnd
        {
            get
            {
                return _contract.HWnd;
            }
        }
        public bool Handled
        {
            get
            {
                return _contract.Handled;
            }
        }
        internal Multitouch.Contracts.Contracts.IPreviewResultContract GetSourceContract()
        {
            return _contract;
        }
    }
}

