//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    [System.AddIn.Pipeline.AddInAdapterAttribute()]
    public class IProviderViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Multitouch.Contracts.Contracts.IProviderContract
    {
        private Multitouch.Contracts.IProvider _view;
        private System.Collections.Generic.Dictionary<Multitouch.Contracts.Contracts.INewFrameEventHandlerContract, System.EventHandler<Multitouch.Contracts.NewFrameEventArgs>> NewFrame_handlers;
        public IProviderViewToContractAddInAdapter(Multitouch.Contracts.IProvider view)
        {
            _view = view;
            NewFrame_handlers = new System.Collections.Generic.Dictionary<Multitouch.Contracts.Contracts.INewFrameEventHandlerContract, System.EventHandler<Multitouch.Contracts.NewFrameEventArgs>>();
        }
        public bool IsRunning
        {
            get
            {
                return _view.IsRunning;
            }
        }
        public bool HasConfiguration
        {
            get
            {
                return _view.HasConfiguration;
            }
        }
        public bool SendEmptyFrames
        {
            get
            {
                return _view.SendEmptyFrames;
            }
            set
            {
                _view.SendEmptyFrames = value;
            }
        }
        public virtual void Start()
        {
            _view.Start();
        }
        public virtual void Stop()
        {
            _view.Stop();
        }
        public virtual System.Windows.UIElement GetConfiguration()
        {
            return _view.GetConfiguration();
        }
        public virtual bool SendImageType(Multitouch.Contracts.Contracts.ImageType imageType, bool value)
        {
            return _view.SendImageType(Multitouch.Contracts.AddInSideAdapters.ImageTypeAddInAdapter.ContractToViewAdapter(imageType), value);
        }
        public virtual void NewFrameAdd(Multitouch.Contracts.Contracts.INewFrameEventHandlerContract handler)
        {
            System.EventHandler<Multitouch.Contracts.NewFrameEventArgs> adaptedHandler = new System.EventHandler<Multitouch.Contracts.NewFrameEventArgs>(new Multitouch.Contracts.AddInSideAdapters.INewFrameEventHandlerContractToViewAddInAdapter(handler).Handler);
            _view.NewFrame += adaptedHandler;
            NewFrame_handlers[handler] = adaptedHandler;
        }
        public virtual void NewFrameRemove(Multitouch.Contracts.Contracts.INewFrameEventHandlerContract handler)
        {
            System.EventHandler<Multitouch.Contracts.NewFrameEventArgs> adaptedHandler;
            if (NewFrame_handlers.TryGetValue(handler, out adaptedHandler))
            {
                NewFrame_handlers.Remove(handler);
                _view.NewFrame -= adaptedHandler;
            }
        }
        internal Multitouch.Contracts.IProvider GetSourceView()
        {
            return _view;
        }
    }
}

