//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts.AddInSideAdapters
{
    
    public class IProviderContractToViewAddInAdapter : Multitouch.Contracts.IProvider
    {
        private Multitouch.Contracts.Contracts.IProviderContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        private Multitouch.Contracts.AddInSideAdapters.IInputEventHandlerViewToContractAddInAdapter Input_Handler;
        private static System.Reflection.MethodInfo s_InputAddFire;
		public event System.EventHandler<Multitouch.Contracts.InputDataEventArgs>Input{
			add{
				if (_Input == null)
				{
					_contract.InputAdd(Input_Handler);
				}
				_Input += value;
				}
			remove{
					_Input -= value;
				if (_Input == null)
				{
					_contract.InputRemove(Input_Handler);
				}
				}
		}
        static IProviderContractToViewAddInAdapter()
        {
            s_InputAddFire = typeof(IProviderContractToViewAddInAdapter).GetMethod("Fire_Input", ((System.Reflection.BindingFlags)(36)));
        }
        public IProviderContractToViewAddInAdapter(Multitouch.Contracts.Contracts.IProviderContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
            Input_Handler = new Multitouch.Contracts.AddInSideAdapters.IInputEventHandlerViewToContractAddInAdapter(this, s_InputAddFire);
        }
        public bool IsRunning
        {
            get
            {
                return _contract.IsRunning;
            }
        }
        public bool HasConfiguration
        {
            get
            {
                return _contract.HasConfiguration;
            }
        }
        private event System.EventHandler<Multitouch.Contracts.InputDataEventArgs> _Input;
        public void Start()
        {
            _contract.Start();
        }
        public void Stop()
        {
            _contract.Stop();
        }
        public System.Windows.UIElement GetConfiguration()
        {
            return _contract.GetConfiguration();
        }
        public bool SendImageType(ImageType imageType, bool value)
        {
            return _contract.SendImageType(Multitouch.Contracts.AddInSideAdapters.ImageTypeAddInAdapter.ViewToContractAdapter(imageType), value);
        }
        internal virtual void Fire_Input(Multitouch.Contracts.InputDataEventArgs args)
        {
            if ((_Input == null))
            {
            }
            else
            {
                _Input.Invoke(this, args);
            }
        }
        internal Multitouch.Contracts.Contracts.IProviderContract GetSourceContract()
        {
            return _contract;
        }
    }
}

