//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts
{
    
    public abstract class InputDataEventArgs : System.EventArgs
    {
        public abstract InputType Type
        {
            get;
        }
        public abstract object Data
        {
            get;
        }
    }
}

