//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts
{
    
    [System.AddIn.Pipeline.AddInBaseAttribute()]
    public interface IProvider
    {
        bool IsRunning
        {
            get;
        }
        bool HasConfiguration
        {
            get;
        }
        event System.EventHandler<InputDataEventArgs> Input;
        void Start();
        void Stop();
        System.Windows.UIElement GetConfiguration();
        bool SendImageType(ImageType imageType, bool value);
    }
}

