//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3069
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multitouch.Contracts
{
    
    public abstract class NewFrameEventArgs : System.EventArgs
    {
        public abstract System.Collections.Generic.IList<IImageData> Images
        {
            get;
        }
        public abstract System.Collections.Generic.IList<IContactData> Contacts
        {
            get;
        }
        public abstract long Timestamp
        {
            get;
        }
    }
}

